
//..........method 1 
// var generateName=require("sillyname");//here generate name is a object imported from module sillyname
// var sillyName=generateName();   //here sillyname is a random name generated 
// console.log(`my name is ${sillyName}`); //through this we will print random name generated by generateName()


//......method 2
// import generateName from "sillyname";

// var sillyName = generateName();

// console.log(`My name is ${sillyName}.`);

//method 3
import superheroe from "superheroes";
 
var name=superheroe.random();
console.log(`hum hai  ${name}.`);



